const colorSchema = {
    MAIN_UI_ACTIVE_COLOR: '#ecbc4d',
    MAIN_UI_DEACTIVE_COLOR: '#646464',
    DARK_UI_BACKGROUND_COLOR: '#2a2a2a',
    DARK_BACKGROUND_COLOR: '#666666',
    DARK_BACKGROUND_COLOR_2: '#363636',
    BTN_BACKGROUND_COLOR_1: '#ecbc4d',
    BTN_BACKGROUND_COLOR_2: '#6d6d6d',
    BTN_BACKGROUND_COLOR_3: '#db3b21',
    TEXT_HEADER_COLOR_1: '#ffffff',
    TEXT_HEADER_COLOR_2: '#fefefe',
    TEXT_HEADER_COLOR_3: '#ababab',
    INPUT_FIELD_PLACE_HOLDER_COLOR: '#7d7d7d',
    INPUT_FIELD_TIPS_COLOR: '#cc7f3f',
    ORDER_BACKGROUND_COLOR: '#444444',
    ORDER_INFO_BACKGROUND_COLOR: '#353535',
    ORDER_TABLE_TITLE_GRAY_COLOR: '#ababab',
    GRADY_BUTTON_BACKGROUND_COLOR: '#8a8a8a',
    GRADY_BUTTON_TEXT_COLOR:'#2a2a2a'
};

export default colorSchema;
